

action_points: &action_points
    new_place: 10
    comment_place: 10
    upvoted_my_comment: 5
    downvoted_my_comment: -2
    vote_comment: 1
    social_recomendation: 10


development:
    <<: *action_points

test:
    <<: *action_points

production:
    <<: *action_points